### ISSUE TITLE
IMU Data Collection

### ISSUE THREAD

**Issue by Kazadhum** [lardemua/atom#1000]
Hi! For my research, I need to save data from IMUs in the ATOM dataset. 

The goal is to then be able to integrate this data to translate it into transformations. As such, a continuous stream of data should be saved. This implies a different system for data collection than used in ATOM thus far. IMU data cannot be saved in "collections" like camera images or LiDAR point clouds.

My current idea is to make use of the `additional_sesor_data` dataset field, changing it to accommodate the saving of continuous data. This change would be additive, so no functionality is lost and hopefully backwards compatibility is preserved. This should be tested when the PR is created.

Below is my TO-DO list for the implementation of this functionality, so it is documented. Development will take place in a separate branch.

---

## TO-DO:
- [x] Create a new system under `atom_examples` called `rihibot` - which is a new version of `rihbot` with an IMU in the end-effector, for testing
- [x] Add support for the IMU sensor modality to `configure_calibration_pkg` so that the `configure` script doesn't return an error
- [x] Implement `continuous` option for the collection of sensor data
- [x] Implement `continuous` option for the collection of `additional_sensor_data` (Not implemented, check #1005)
- [ ] Write the documentation for `rihibot`

This list will be updated as I progress and possibly find more obstacles.

Tagging @miguelriemoliveira @rarrais for visibility.

**Comment by Kazadhum** [comment]
I'm running into a small issue...

I get this error when running `rosrun rihibot_calibration configure`:

```
ATOM Error: Sensor imu calibration config defined link imu_link but bagfile messages on topic /imu have header.frame_id wrist_3_link. These should be the same! Check #514.
```

This prompted my to check the messages being published under the `/imu` topic:

```
header: 
  seq: 16514
  stamp: 
    secs: 2674
    nsecs:  11000000
  frame_id: "wrist_3_link"
orientation: 
  x: 0.6987632116657506
  y: 0.1087786864452839
  z: -0.6940625160617692
  w: -0.13481244451389074
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.00018741384054262985
  y: -0.0052810690874827634
  z: -0.006005440687883528
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -1.277917167846468e-11
  y: 1.4583417090238843e-11
  z: -1.522552128873299e-11
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

The `frame_id` in the message is set to `"wrist_3_link"`. However, the IMU plugin in configured to consider the frame `imu_link`...

https://github.com/lardemua/atom/blob/ce1aa71f736bad63e14c98f50fd86b7a93470737/atom_examples/rihibot/rihibot_description/urdf/imu.urdf.xacro#L45-L72

Looking at the TF tree using RQT:

![Image](https://github.com/user-attachments/assets/846554ca-1010-4b7c-8fd8-c8c50da27f02)

The documentation for the plugin is scarce, so I couldn't find anything on this, but I believe what is happening is the IMU plugin ignoring the fixed TFs, such as the wrist-3-to-flange and flange-to-imu_link. I think I'll continue developing using `softbot` to test but I will circle back to this.

**Comment by Kazadhum** [comment]
I just checked the [source code](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/959e7d02ecb8d0c8940623921220ce960542f6c7/gazebo_plugins/src/gazebo_ros_imu.cpp#L279C11-L279C35) for the `libgazebo_ros_imu` plugin and my previous assertion doesn't make sense... There is no place in the code where either `frameName` or `frame_id` are changed w.r.t. fixed TF's

**Comment by miguelriemoliveira** [comment]
Hey @Kazadhum ,

not sure what is happening, but from what I gather the problem is not in atom right?

Can you point to the IMU plugin code?

**Comment by Kazadhum** [comment]
Hello @miguelriemoliveira! Yeah, the problem isn't in ATOM, but in the gazebo plugin, I think. 

Here's the [gazebo plugin source code](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/959e7d02ecb8d0c8940623921220ce960542f6c7/gazebo_plugins/src/gazebo_ros_imu.cpp), and here's my use of the plugin in the URDF:

https://github.com/lardemua/atom/blob/ce1aa71f736bad63e14c98f50fd86b7a93470737/atom_examples/rihibot/rihibot_description/urdf/imu.urdf.xacro#L45-L72

**Comment by miguelriemoliveira** [comment]
Hum. This sounds like black magic ...

here the this->frame_name_ is used to set the frame in the message.

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/959e7d02ecb8d0c8940623921220ce960542f6c7/gazebo_plugins/src/gazebo_ros_imu.cpp#L278-L281

So what happens if you just delete these two from the xacro?

			<bodyName>imu_link</bodyName>
			<frameName>imu_link</frameName>

**Comment by Kazadhum** [comment]
If I delete those two lines, I get this error in gazebo:

`[FATAL] [1737370228.346497682, 3310.400000000]: imu plugin missing <bodyName>, cannot proceed`

which makes sense, given this:

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/959e7d02ecb8d0c8940623921220ce960542f6c7/gazebo_plugins/src/gazebo_ros_imu.cpp#L97-L100

**Comment by Kazadhum** [comment]
Using only `<bodyName>`, I get:

`[ INFO] [1737370389.539868998, 2574.721000000]: imu plugin missing <frameName>, defaults to <bodyName>`
which also makes sense given the source code. 

The IMU is publishing data but it still has `wrist_3_link` as its frame_id.

**Comment by Kazadhum** [comment]
I just checked and the same thing happens with `softbot`... Maybe I have to use the alternative `libgazebo_ros_imu_sensor` plugin? I never got it to work properly before, but I can try again.

**Comment by Kazadhum** [comment]
Ok so I added the `libgazebo_ros_imu_sensor` plugin and I think it is working properly! The only thing to account for is that this plugin does measure gravity, so this must be considered in any algorithm that uses this data.

However, the IMU messages now have the proper `header_id`!

```
header: 
  seq: 9766
  stamp: 
    secs: 2722
    nsecs: 380000000
  frame_id: "imu_link"
orientation: 
  x: -0.0028736304093780474
  y: 0.03402877967051662
  z: -0.9956221813167769
  w: -0.08700722080625889
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.021119082716111827
  y: 0.003690111404028421
  z: 7.822583583077104e-05
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.11410727924185207
  y: -0.6591437516596792
  z: 9.777142752129746
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

So I think this roadblock is gone
