### ISSUE TITLE
Document the template files. Improve readability of `config.yml`.

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/atom#182]
For those that open the generated files and want to known it each file does.

The `config.yml` uses the old JSON format. Now that we are using YAML we may use the less verbose lexical to define dictionaries.
```yaml
{ 
  "key" : {  
     "sub-key" : "value",
      "another-key": true 
  }
}
```
is equivalent to
```yaml
key:
  sub-key: "value"
  another-key: true
```
