### ISSUE TITLE
Check eye_to_base

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#194]

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa ,

will you have time for this?

**Comment by eupedrosa** [comment]
Sorry, not until next week. But the only thing that you need is the correct pattern parameters. And here they are:

```yaml
- paper Charuco DICT_4X4
  x: 8, y: 5
  size: 0.029
  inner: 0.021

- Charuco from Calib.io
  x: 13, y: 8
  size: 0.02
  inner: 0.015
  outter: 0.01

- paper Chessboard
  x: 9, y: 7
  size: 0.019
  outter: 0.02
```
