### ISSUE TITLE
Integration with rviz panel - set initial estimate - Buttons for save and reset

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#280]
Hi @MiguelDRPina

About the buttons for saving and reset, there is a topic **/set_initial_estimate/feedback**
on which rviz publishes a msg everytime the user presses either the save or the reset button.

You can listen to the topic using

`rostopic echo /set_initial_estimate/feedback`

and then pressing the buttons (right click the sphere of any contro and a menu pops upl).

Doing this you get **for when the save button is pushed** a message like this:

```yaml
header: 
  seq: 0
  stamp: 
    secs: 822
    nsecs: 109000000
  frame_id: "ee_link"
client_id: "/rviz/MoveSensors-InteractiveMarker"
marker_name: "hand_camera"
control_name: ''
event_type: 2
pose: 
  position: 
    x: -0.019999999552965164
    y: 0.05000000074505806
    z: 0.07000000029802322
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
menu_entry_id: 1
mouse_point: 
  x: -0.07335437089204788
  y: 0.07233176380395889
  z: 0.11905686557292938
mouse_point_valid: True
---
```

Doing this you get **for when the reset  button is pushed** a message like this:

```yaml
header: 
  seq: 0
  stamp: 
    secs: 868
    nsecs: 649000000
  frame_id: "ee_link"
client_id: "/rviz/MoveSensors-InteractiveMarker"
marker_name: "hand_camera"
control_name: ''
event_type: 2
pose: 
  position: 
    x: -0.019999999552965164
    y: 0.05000000074505806
    z: 0.07000000029802322
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
menu_entry_id: 2
mouse_point: 
  x: -0.03277934342622757
  y: 0.06772848218679428
  z: 0.1465941220521927
mouse_point_valid: True
---
```

All you have to do is to send a message similar to the one you see above when your save and reset buttons are pressed.
