### ISSUE TITLE
RGBD camera simulation in gazebo is not using the proper frame ids

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#327]
From the test we made there is only one frame id we can set in the gazebo plugin, and in fact for an RGBD camera we should need two frame ids.

The idea is to try to configure two sensors withtin a single **gazebo reference group** or alternatively, create two gazebo references per camera, one with contains and RGBD camera where the rgb topics are ignored (because we know they are in the wrong place) and a second gazebo component with a rgb camera.

**Comment by miguelriemoliveira** [comment]
Test2 bag and dataset are here
[test2.zip](https://github.com/lardemua/atom/files/7512364/test2.zip)

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

I think I managed to separate the two components... Can you test please?

**Comment by danifpdra** [comment]
I am still getting a disparity tho 

![image](https://user-images.githubusercontent.com/47574905/141174959-022119f2-4628-41c1-976f-cc60fa631a0f.png)

**Comment by miguelriemoliveira** [comment]
Hum, something is wrong. I will check but I don't know if I can do it tonight.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I could not resist testing. 

So I see that we have some confusing topic names:

```
/world_camera/camera_info
/world_camera/depth/camera_info
/world_camera/depth/image_raw
/world_camera/image_raw
/world_camera/rgb/camera_info
/world_camera/rgb/image_raw
```

So depth is ok, this command

`rostopic echo /world_camera/depth/image_raw --noarr`

returns

```
header: 
  seq: 3
  stamp: 
    secs: 744
    nsecs: 420000000
  frame_id: "world_camera_depth_optical_frame"
height: 720
width: 1280
encoding: "32FC1"
is_bigendian: 0
step: 5120
data: "<array type: uint8, length: 3686400>"

```
Which has the correct frame_id.

Now for the rgb, I am not sure which is the real one. The other one should have a null topic name so we don't get confused. Something like /null or something.

If it is the **world_camera/rgb**, the command

`rostopic echo /world_camera/rgb/image_raw --noarr`

returns 

```
header: 
  seq: 587
  stamp: 
    secs: 801
    nsecs: 919000000
  frame_id: "world_camera_rgb_optical_frame"
height: 720
width: 1280
encoding: "bgr8"
is_bigendian: 0
step: 3840
data: "<array type: uint8, length: 2764800>"
```
which is correct in the frame_id.

Now if it is the **/world_camera/image_raw** command

`rostopic echo /world_camera/image_raw --noarr`

results in

```
header: 
  seq: 21
  stamp: 
    secs: 845
    nsecs: 196000000
  frame_id: "world_camera_depth_optical_frame"
height: 720
width: 1280
encoding: "bgr8"
is_bigendian: 0
step: 3840
data: "<array type: uint8, length: 2764800>"
```
which has an incorrect frame id. 

The incorrect camera should have a null name to avoid confusions.

About the thing you say it all stays the same this is strange. Do the test I told you, change the xacro to put the rgb camera 2 meters to the right ... does the rgb image change? It must.

You could also try my idea of having two separate    **<gazebo reference="${prefix}_link">** sections.
