### ISSUE TITLE
Create ids to identify sensors to label instead of identification through message type

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#328]

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

my suggestion is to have in the calibration yaml, for each sensor,  something like an additional key called **labeller**  where we define the labeller we want to use.

This is an optional key, if labeller is not there in the sensor section the default labeller derived from the msg type of the topic specified in **topic_name** is used (what we do right now).

```yml
# ATOM will calibrate the extrinsic parameters of your sensors.
# In this section you should discriminate the sensors that will be part of the calibrations.
sensors:
    hand_camera:
        link: "hand_camera_rgb_optical_frame"
        parent_link: "flange"
        child_link: "hand_camera_link"
        topic_name: "/hand_camera/rgb/image_raw"
        throttle: 5
        labeller: 'camera_labeller'

    lidar:
        link: "lidar"
        parent_link: "tripod_left_support"
        child_link: "lidar_base_link"
        topic_name: "/lidar/points"
        # No labeller, derive labeller from type of message in topic topic_name
```

Does it make sense to you?
