### ISSUE TITLE
Collector crashes

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#332]
Another bug when runniong hte collector

> roslaunch mmtbot_calibration collect_data.launch output_folder:=/home/mike/datasets/mmtbot/test_depth2 overwrite:=true

> [ERROR] [1637347633.427798, 706.815423]: bad callback: <bound method InteractiveDataLabeler.sensorDataReceivedCallback of <atom_calibration.collect.interactive_data_labeler.InteractiveDataLabeler object at 0x7f27ef7fc550>>
> Traceback (most recent call last):
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
>     cb(msg)
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 242, in sensorDataReceivedCallback
>     self.labelData  # label the data
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 683, in labelData
>     self.labels, seed_point, inliers = labelPointCloud2Msg(self.msg, x_marker, y_marker, z_marker,
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/label_messages.py", line 24, in labelPointCloud2Msg
>     points[:, 0] = pc['x'].flatten()  # flatten because some pcs are of shape (npoints,1) rather than (npoints,)
> ValueError: could not broadcast input array from shape (921600,) into shape (720,)

I think this is from your side right?

**Comment by miguelriemoliveira** [comment]
I know you are not on the computer now, I will pick this up tomorrow again.

**Comment by danifpdra** [comment]
Are you trying to calibrate depth points? That was the error that was showing when I did that

**Comment by miguelriemoliveira** [comment]
Yes. I was just using the calibration.yam as you pushed it ... tomorrow i
can try with a different yaml

**Comment by miguelriemoliveira** [comment]
Humm, actually I don't think I am calibrating depth. Look at the calibration.yml, there is no depth there.

Also, you did not change sensor_id -> modality yet (and put modality to the bottom, since its optional).

```
    # Example:
    hand_camera:
        sensor_id: rgb
        link: "hand_camera_rgb_optical_frame"
        parent_link: "flange"
        child_link: "hand_camera_link"
        topic_name: "/hand_camera/rgb/image_raw"
        throttle: 5
#
#    world_camera:
#        sensor_id: rgb
#        link: "world_camera_rgb_optical_frame"
##        parent_link: "tripod_right_support"
##        child_link: "world_camera_link"
#        parent_link: "tripod_plate"
#        child_link: "tripod_right_support"
#        topic_name: "/world_camera/rgb/image_raw"


    lidar:
        sensor_id: lidar
        link: "lidar"
        parent_link: "tripod_left_support"
        child_link: "lidar_base_link"
        topic_name: "/lidar/points"

    world_camera_depth:
        sensor_id: lidar
        link: "world_camera_depth_optical_frame"
        parent_link: "tripod_plate"
        child_link: "tripod_right_support"
        topic_name: "/world_camera/depth/points"
```

When you make these changes let me know so I can test again ok?
