### ISSUE TITLE
Too many measurements at collect data step

### ISSUE THREAD

**Issue by sensorCalib** [lardemua/atom#498]
Hi,

at step 4. when trying to collect data, we seem to get a dimension mismatch. This is the error occuring:

`[ERROR] [1656064461.734798, 1656052507.736720]: bad callback: <bound method InteractiveDataLabeler.sensorDataReceivedCallback of <atom_calibration.collect.interactive_data_labeler.InteractiveDataLabeler object at 0x7f3929d15d60>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/user/ws/src/atom-calibration/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 295, in sensorDataReceivedCallback
    self.labelData()  # label the data
  File "/home/user/ws/src/atom-calibration/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py", line 464, in labelData
    self.labels, seed_point, inliers = labelPointCloud2Msg(self.msg, x_marker, y_marker, z_marker,
  File "/home/user/ws/src/atom-calibration/atom_calibration/src/atom_calibration/collect/label_messages.py", line 45, in labelPointCloud2Msg
    points[:, 0] = pc['x'].flatten()  # flatten because some pcs are of shape (npoints,1) rather than (npoints,)
ValueError: could not broadcast input array from shape (65536) into shape (64)`

We have 64 lines with 1024 measurement-values each, which results in the 65536 measurements.
However, only one measurment per coordinate is expected.

Any idea how to fix this? Thank you very much.

**Comment by miguelriemoliveira** [comment]
Hello,

Before we help, could you please provide more information? What robotic system are you calibrating? How many sensors? Of which modality?

It seems you have just created this account in github. Also, you do not identify yourself. If you could provide some more information that would be very helpful.

**Comment by sensorCalib** [comment]
Hello,

thanks for the feedback, I'll gladly provide you with more information.

Robotic system: ROS Noetic, working with noetic-devel branch
How many sensors: two (ouster os1, zed 2i) The error happens with the ouster.
Which modality: ouster os1 has modality lidar3d, zed 2i has modality rgb

I am a commercial user and working on a research project about environment detection.

**Comment by miguelriemoliveira** [comment]
Hi @sensorCalib ,

I have never worked with this sensor before, but it should be very similar to velodyne.

To investigate I would need your calibration.yml file (or a link to your calibration repository) and also a bag file with the sensor data. IT can be just a small 1 min bag or something.

Could you provide this please?

**Comment by sensorCalib** [comment]
Hello @miguelriemoliveira ,

yes, of course I can share these files with you. The bag files become quite huge quickly, so I only recorded several seconds. Hopefully, this is sufficient.

https://www.dropbox.com/scl/fo/o40e4s4vu32bpn99p1j2e/h?dl=0&rlkey=0ugua76pvhx1jsnxwbvanyz6p

**Comment by miguelriemoliveira** [comment]
Hi @sensorCalib ,

I have downloaded the bag and yml. Thanks. 

SI created a calibration package of my own since you did not share yours, but now to configure the calibration package I need this xacro file:

"/home/user/ws/src/base/description/urdf/system.urdf.xacro"

Can you provide it?

Thanks

**Comment by miguelriemoliveira** [comment]
I have compared the ouster lidar ros messages that you have 

```
header: 
  seq: 1284
  stamp: 
    secs: 1656052510
    nsecs: 181796381
  frame_id: "ouster_os1_0_base_link"
height: 64
width: 1024
fields: "<array type: sensor_msgs/PointField, length: 9>"
is_bigendian: False
point_step: 48
row_step: 49152
data: "<array type: uint8, length: 3145728>"
is_dense: True
```

with the ones we use from velodynes:

```
header: 
  seq: 6319
  stamp: 
    secs: 1649240013
    nsecs: 829686165
  frame_id: "lidar_1"
height: 1
width: 26808
fields: "<array type: sensor_msgs/PointField, length: 6>"
is_bigendian: False
point_step: 22
row_step: 589776
data: "<array type: uint8, length: 589776>"
is_dense: True
```

I think the problem is, as you discussed above, the fact that the ouster point cloud is not flattened (i.e. height=1) as is the velodyne point cloud.

Let me investigate further.
