### ISSUE TITLE
Check consistency in sensor frame_id in topics and calibration.yaml

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#514]
In #498 I used a configuration where the calibration.yaml said the sensor data was in one tf frame, and then it was in another.

The Calibration.yaml

```yaml
  ouster_os1:
    link: "ouster_os1_0_lidar_center"
    parent_link: "base_link"
    child_link: "ouster_os1_0_base_link"
    topic_name: "/ouster_cloud_os1_0/points"
    #throttle: 10
    modality: lidar3d

```
and the calibration configuration report:

![image](https://user-images.githubusercontent.com/11350998/180617054-2988a1e6-6c3e-4cf0-965b-79c481fa1527.png)

But when we run a rostopic echo of the **/ouster_cloud_os1_0/points** topic we get

```bash
header: 
  seq: 1268
  stamp: 
    secs: 1658155460
    nsecs: 245768772
  frame_id: "ouster_os1_0_base_link"
height: 64
width: 1024
fields: "<array type: sensor_msgs/PointField, length: 9>"
is_bigendian: False
point_step: 48
row_step: 49152
data: "<array type: uint8, length: 3145728>"
is_dense: True
```

Here it says the frame_id was the **ouster_os1_0_base_link**, and in the configuration it said the  frame is **ouster_os1_0_lidar_center**.

This is causing all sorts of problems later on.

The calibration package configuration  should notice this and abort with an error message.
