### ISSUE TITLE
New stuff to support in config.yml and dataset v 2.0

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#731]
- [x] Multiple calibration patterns
- [x] Joints
- [x] Remove joints: "" and move to format joints: 
- [x] Remove addtional_tfs: "" and move to format addtional_tfs: 
- [x] joints will loose parent and child and get same name as urdf
- [x] All fields in config.yml are mandatory, even if they are not on the first level
- [x] Add version to config

**Comment by manuelgitgomes** [comment]
Additional tfs and joints are now mandatory!

**Comment by miguelriemoliveira** [comment]
In #728 created a script to update config,yml files to version 2.0.

Already advanced all config files in atom examples to v2.0.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes , since you are working on the datasets then I should be hands off, right?

I think it is better to have a single person working on all this at the same time, as there are many interconnections ...

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira, I will be leaving for today, so please continue.

In the last commit I created a first version of dataset conversion
This version only consists of adding additional_tfs, joints, package_name and changing the dataset version.

**Comment by miguelriemoliveira** [comment]
configure_calibration_pkg seems ok. Moving on to collect_data

**Comment by miguelriemoliveira** [comment]
I am halfway through correcting the collect and label script.

Only tomorrow afternoon I will come back to this.

@manuelgitgomes if you want, advance with the dataset converter. I will call when I start working again so we can sync.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira.

I am now going for lunch, so I will just update you on what I am doing.

I found we have some mistakes on config conversion:

- We do not add modality nor throttle to sensors that do not have them
- We convert all non string values to string (booleans for defining pattern as fixed, numbers for pattern size, etc), this could cause errors along the line. If you think not, tell me please.

I am trying to fix those

**Comment by manuelgitgomes** [comment]
Commit 8b1d156090be56bcfd6640a08a2c82193631dcf0 adds:

For config conversion:
Solved import errors with config_io
Verifies if version is bellow 2.0
Changes backup name to be consistent with dataset conversion
Solved bug that would crash if the old config did not have add_tfs or joints
Added support for giving throttle and modality for sensors who don't have it
In the template, defined some properties to not be string.

For dataset_conversion:
Changes backup name to be consistent with config conversion

**Comment by miguelriemoliveira** [comment]
Thanks. I will continue to work on the data_collector producing a correct dataset format.

Will keep you posted.

**Comment by manuelgitgomes** [comment]
> Thanks. I will continue to work on the data_collector producing a correct dataset format.

I was working on that, do you want me to commit my findings and you keep working?

**Comment by miguelriemoliveira** [comment]
No, no, if you are working on that continue. I will then work of bringing the atom examples back to operational status.

**Comment by manuelgitgomes** [comment]
We can also change anchored_sensor from "" to null, right?

**Comment by miguelriemoliveira** [comment]
Right. I think makes more sense.

I like that in configure_calibartion_pkg we have a standarized way of testing, e.g.:

```python
if config['joints'] is not None:
  do stuff
```

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

when you leave work this afternoon please push and  let me know where you are.
I will pick it up tonight.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira.

Sorry, I had a meeting that took a big part of the afternoon so I had to drop this in the middle.
As I did not want to push something half-baked, I finished everything now, so only now I have pushed a lot of commits.

Trying to make a summary:

- I changed anchored sensor from '' to null and adapted everything for it
- Solved a bug that when 'toggle' was null, the toggle nodes were still launched, causing in error
- In "non-essential" scripts, I implemented the simple solution of changing the 'calibration_pattern' to the first element of 'calibration_patterns'
- I added support for multiple patterns in data collector. Should theoretically work right out of the box if we implemented now the multiple patterns. (I would still be very VERY surprised nonetheless if it did). 
To do this, I moved all the labels (`dataset['collections'][collection_key]['labels']`) to a dictionary with the name `pattern_1` (`dataset['collections'][collection_key]['labels']['pattern_1']`
- Updated the dataset updated, to be up to date with the previous changed

Please test data collection and dataset conversion.
If everything is ok, we can would now on the calibrate script.
I will continue working on this tomorrow morning.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

thanks for the update. I will try it out and let you know. Probably tonight or tomorrow.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!

I will be seeing if setting initial estimate and dataset_playback are functional and if not, fixing them.

After I have done that, I will report back.

**Comment by miguelriemoliveira** [comment]
Thanks. I am creating a new atom_example called eye_in_world_system so I can test everything from scratch, i.e. without the updaters.

One thing I changed to be consistent with the global philosophy is this:

```yml
  # throttle:
  #   Set throttle: desired_frame_rate. If you don't use throttle, do not enter a value, i.e. "throttle: "
  #
  # If you are using an image compressed topic such as:
  #   /world_camera/rgb/image_raw/compressed
  # you should not add the "compressed" part, use only:
  #   /world_camera/rgb/image_raw
  #

  hand_camera:
    link: "hand_camera_optical_frame"
    parent_link: "end_effector"
    child_link: "hand_camera"
    topic_name: "/hand_camera/image_raw"
    modality: "rgb"
    throttle: 10


  # You can have more than one sensor:
  another_camera:
    link: "another_camera_optical_frame"
    parent_link: "end_effector"
    child_link: "another_camera"
    topic_name: "/another_camera/image_raw"
    modality: "rgb"
    throttle:
```

I have fixed a lot of stuff already so I will push it right now.
