### ISSUE TITLE
Bagfile for spjbot in atom examples missing

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#859]
Hey,

I noticed I didn't have any bagfile for spjbot.

I tried downloading again the files by executing 

`rosrun atom_calibration download_atom_examples_data `

And nothing downloaded regarding spjbot.

I downloaded this bagfile referenced in the spjbot's readme :
https://github.com/lardemua/atom/blob/57c8407ffc3309d12649e60cdb4f94b0c473725e/atom_examples/spjbot/README.md#L37-L38

But this bafile's joint_state message doesn't match the joints defined in the scara_xacro urdf, hence popping up this error when running the configuration :
`ATOM Error: Bagfile /joint_states message do not contain joint ['j1_joint', 'j2_joint', 'j3_joint', 'j4_joint'] (wrist_3_joint in bagfile)`

Which I checked and validated by running the bagfile and echo'ing the /joint_state message

```
header: 
  seq: 44386
  stamp: 
    secs: 2665
    nsecs: 283000000
  frame_id: ''
name: 
  - elbow_joint
  - shoulder_lift_joint
  - shoulder_pan_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
position: [0.3768785831792094, -0.8497662110263313, -1.4176506551958186, -0.9177547060502302, -1.7342235011927372, -2.6839941245174783]
velocity: [0.0004162651498339359, 0.019066057811052445, -0.00023113907204973794, 0.0003425896073790541, -2.1663502830267488e-05, 2.3462068841774864e-05]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

And the names don't match.

@miguelriemoliveira if you don't have the correct bagfile, I can record a new one to replace it.
