### ISSUE TITLE
Executing softbot experiments

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#948]
This issue is a followup of #926.

I have everything ready to run the experiments tonight. I'm not sure my pc will handle it well considering that calibrating the odom tf adds a lot more optimization parameters, will see.

# I was missing `-atsf`

This was something critical that was actually missing, my baseline. I have updated the template to add this feature and right now its like this : 

```
     ...
     rosrun atom_calibration calibrate -json {{ dataset_path }}/dataset_corrected.json \
          -v  -ss {{ run }} \
          -nig {{ e.nig_value }} {{ e.nig_value }} \
          -csf 'lambda x: int(x) in {{ fold[0] }}' \
          -ntfv {{ e.ntfv_value }} {{ e.ntfv_value }} \
          -ntfl "world:base_footprint" \
          -sce \
          {% if not e.calibrate_odom -%}
            -atsf 'lambda name : name in []' \
          {%- endif %}
          && \
          ...
```

Basically in some experiments I have a boolean excluding all additional tf's.

Im not sure how to evenly distribute all the variance of all variables I want to study. Rn I'm varying `nig` , and `ntfv` between 0 and 3 m/rad and `atsf` between true/false. I feel I have way too many experiences for my pc to handle in feasible time. 

This is my `data.yml` at the moment : 

```
#
#           █████╗ ████████╗ ██████╗ ███╗   ███╗
#          ██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║
#          ███████║   ██║   ██║   ██║██╔████╔██║
#          ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║
#   __     ██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║    _
#  / _|    ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝   | |
#  | |_ _ __ __ _ _ __ ___   _____      _____  _ __| | __
#  |  _| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /
#  | | | | | (_| | | | | | |  __/\ v  v / (_) | |  |   <
#  |_| |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\
#  https://github.com/lardemua/atom

# this yml file contains variables to be used in conjunction with batch.yml

# Auxiliary variables, to be used to render other fields in the template.yml.j2 file
package_path: "package://softbot_calibration"
dataset_path: '$ATOM_DATASETS/softbot/long_train_dataset1'
collections_to_remove: [27,36,37]

# Runs are repetitions of the experiments for gathering statistically significant results
runs: [1,2,3]
  
cross_validation:
  type: "stratified-k-fold" 
  n_splits: 5 # Number of folds
  train_size:  # Percentage of the dataset used for training, only used in StratifiedShuffleSplit

# Experiments are executions with a set of input parameters
experiments:
# Varying noise from 0 to 0.3m/rad

# --------------------
# Calibrating odom
# --------------------

  # Perfect Simulation
  - {name: perfect_sim, nig_value: 0.0, ntfv_value: 0.0, calibrate_odom : true}

  # Varying nig only
  - {name: nig_0.1,  nig_value: 0.1,  ntfv_value: 0.0,  calibrate_odom : true}
  - {name: nig_0.15, nig_value: 0.15, ntfv_value: 0.0,  calibrate_odom : true}
  - {name: nig_0.2,  nig_value: 0.2,  ntfv_value: 0.0,  calibrate_odom : true}
  - {name: nig_0.25, nig_value: 0.25, ntfv_value: 0.0,  calibrate_odom : true}
  - {name: nig_0.3,  nig_value: 0.3,  ntfv_value: 0.0,  calibrate_odom : true}

    #Varying ntfv with fixed nig = 0.1
  - {name: nig_0.1-ntfv_0.1 ,  nig_value: 0.1,  ntfv_value: 0.1,   calibrate_odom : true}
  - {name: nig_0.1-ntfv_0.15,  nig_value: 0.1,  ntfv_value: 0.15,  calibrate_odom : true}
  - {name: nig_0.1-ntfv_0.2 ,  nig_value: 0.1,  ntfv_value: 0.2,   calibrate_odom : true}
  - {name: nig_0.1-ntfv_0.25,  nig_value: 0.1,  ntfv_value: 0.25,  calibrate_odom : true}
  - {name: nig_0.1-ntfv_0.3 ,  nig_value: 0.1,  ntfv_value: 0.3,   calibrate_odom : true}
  
  #   #Varying ntfv with fixed nig = 0.15 
  - {name: nig_0.15-ntfv_0.1,  nig_value: 0.15, ntfv_value: 0.1,  calibrate_odom : true}
  - {name: nig_0.15-ntfv_0.15, nig_value: 0.15, ntfv_value: 0.15, calibrate_odom : true}
  - {name: nig_0.15-ntfv_0.2,  nig_value: 0.15, ntfv_value: 0.2,  calibrate_odom : true}
  - {name: nig_0.15-ntfv_0.25, nig_value: 0.15, ntfv_value: 0.25, calibrate_odom : true}
  - {name: nig_0.15-ntfv_0.3,  nig_value: 0.15, ntfv_value: 0.3,  calibrate_odom : true}
  
  #   #Varying ntfv with fixed nig = 0.2
  - {name: nig_0.2-ntfv_0.1 , nig_value: 0.2, ntfv_value: 0.1,  calibrate_odom : true}
  - {name: nig_0.2-ntfv_0.15, nig_value: 0.2, ntfv_value: 0.15, calibrate_odom : true}
  - {name: nig_0.2-ntfv_0.2 , nig_value: 0.2, ntfv_value: 0.2,  calibrate_odom : true}
  - {name: nig_0.2-ntfv_0.25, nig_value: 0.2, ntfv_value: 0.25, calibrate_odom : true}
  - {name: nig_0.2-ntfv_0.3 , nig_value: 0.2, ntfv_value: 0.3,  calibrate_odom : true}
  
  #   #Varying ntfv with fixed nig = 0.25 
  - {name: nig_0.25-ntfv_0.1,  nig_value: 0.25, ntfv_value: 0.1,  calibrate_odom : true}
  - {name: nig_0.25-ntfv_0.15, nig_value: 0.25, ntfv_value: 0.15, calibrate_odom : true}
  - {name: nig_0.25-ntfv_0.2,  nig_value: 0.25, ntfv_value: 0.2,  calibrate_odom : true}
  - {name: nig_0.25-ntfv_0.25, nig_value: 0.25, ntfv_value: 0.25, calibrate_odom : true}
  - {name: nig_0.25-ntfv_0.3,  nig_value: 0.25, ntfv_value: 0.3,  calibrate_odom : true}
  
  #   #Varying ntfv with fixed nig = 0.3
  - {name: nig_0.3-ntfv_0.1,  nig_value: 0.3, ntfv_value: 0.1,  calibrate_odom : true}
  - {name: nig_0.3-ntfv_0.15, nig_value: 0.3, ntfv_value: 0.15, calibrate_odom : true}
  - {name: nig_0.3-ntfv_0.2,  nig_value: 0.3, ntfv_value: 0.2,  calibrate_odom : true}
  - {name: nig_0.3-ntfv_0.25, nig_value: 0.3, ntfv_value: 0.25, calibrate_odom : true}
  - {name: nig_0.3-ntfv_0.3,  nig_value: 0.3, ntfv_value: 0.3,  calibrate_odom : true}

# --------------------
# Not calibrating odom
# --------------------
#
# Not sure which to repeat without calibrating odom
  - {name: nig_0.2_no_odom_calib,           nig_value: 0.2,  ntfv_value: 0.0,  calibrate_odom : false}
  - {name: nig_0.2-ntfv_0.2_no_odom_calib,  nig_value: 0.2,  ntfv_value: 0.2,  calibrate_odom : false}

```
