### ISSUE TITLE
Upgrade process_results to include plots

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#951]
I find comparing and analyzing the results after a batch very time-consuming and prone to error.

It would be great if the processing also outputted a plot of the results.

There is a problem with this though. This requires ATOM to know which experiments are related and which are not.

For example in this tree : ( from my odometry experiments)
```

├── nig_0.1
├── nig_0.15
├── nig_0.15-ntfv_0.1
├── nig_0.15-ntfv_0.15
├── nig_0.15-ntfv_0.2
├── nig_0.15-ntfv_0.25
├── nig_0.15-ntfv_0.3
├── nig_0.1-ntfv_0.1
├── nig_0.1-ntfv_0.15
├── nig_0.1-ntfv_0.2
├── nig_0.1-ntfv_0.25
├── nig_0.1-ntfv_0.3
├── nig_0.2
├── nig_0.25
├── nig_0.25-ntfv_0.1
├── nig_0.25-ntfv_0.15
├── nig_0.25-ntfv_0.2
├── nig_0.25-ntfv_0.25
├── nig_0.25-ntfv_0.3
├── nig_0.2_no_odom_calib
├── nig_0.2-ntfv_0.1
├── nig_0.2-ntfv_0.15
├── nig_0.2-ntfv_0.2
├── nig_0.2-ntfv_0.25
├── nig_0.2-ntfv_0.2_no_odom_calib
├── nig_0.2-ntfv_0.3
├── nig_0.3
├── nig_0.3-ntfv_0.1
├── nig_0.3-ntfv_0.15
├── nig_0.3-ntfv_0.2
├── nig_0.3-ntfv_0.25
├── nig_0.3-ntfv_0.3
└── perfect_sim
```

How would you know which experiments were part of the same plot?

My first guess was to compare which experiments had the same alphabetic characters but this is very easily prone to a lot of error. 

These 2 for example should be on the same plot:

```
├── nig_0.3-ntfv_0.2
├── nig_0.3-ntfv_0.25
```

But this shouldn't even though they have same alphabetic chars.

`├── nig_0.2-ntfv_0.2`

There is no way for the code to know which experiments are related.

There is a super easy fix but would break backwards compatibility : Add a field in `data.yml` called `groups`, like so : 

```
experiments:
  
  group_1:  
      #Varying ntfv with fixed nig = 0.1
    - {name: nig_0.1-ntfv_0.1 ,  nig_value: 0.1,  ntfv_value: 0.1,   calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.15,  nig_value: 0.1,  ntfv_value: 0.15,  calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.2 ,  nig_value: 0.1,  ntfv_value: 0.2,   calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.25,  nig_value: 0.1,  ntfv_value: 0.25,  calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.3 ,  nig_value: 0.1,  ntfv_value: 0.3,   calibrate_odom : true}

  group_2:
      #Varying ntfv with fixed nig = 0.2
    - {name: nig_0.1-ntfv_0.1 ,  nig_value: 0.2,  ntfv_value: 0.1,   calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.15,  nig_value: 0.2,  ntfv_value: 0.15,  calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.2 ,  nig_value: 0.2,  ntfv_value: 0.2,   calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.25,  nig_value: 0.2,  ntfv_value: 0.25,  calibrate_odom : true}
    - {name: nig_0.1-ntfv_0.3 ,  nig_value: 0.2,  ntfv_value: 0.3,   calibrate_odom : true}
```

I'll work on this even if its just for myself and if it proves useful we consider making it on to `noetic-devel`
