### ISSUE TITLE
List of preliminary assessments before doing batches for Odometry paper

### ISSUE THREAD

**Issue by brunofavs** [lardemua/atom#983]
As we're coming back from the summer, in order to freshen up the point where we left things off with ZAU, I wrote a list of preliminary tests we should do before committing to doing long experiment batches.

Considering all the variables we have at play :
### Datasets
- [x] Dataset without corrected odometry
- [x] Dataset with corrected odometry
- [x] Dataset with corrected odometry and depth

### Which sensors to calibrate:

Steps:

- [x] 1 RGB
- [x] 2 RGB
- [x] 3 RGB + Depth ( the 3rd RGB comes from the rgbd camera)
- [x] 3 RGB + Depth + LiDAR

Fisheyes are out because we don't have a method to manually label them.

### Calibrating odometry

 - [x]  With and without my MsC. thesis methodology

Tagging @manuelgitgomes @miguelriemoliveira @Kazadhum for visibility.

**Comment by Kazadhum** [comment]
We're also expecting to have to correct the hand RGB camera pose in the initial guess

**Comment by miguelriemoliveira** [comment]
Makes sense.

**Comment by brunofavs** [comment]
Hey, last night I ran some of the tests mentioned in the checklist.

These tests were run with the datasets @miguelriemoliveira sent me and @Kazadhum yesterday by email. 

# Comands for each test

#### Dataset corrected

1 RGB

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json
&& rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```


2 RGB

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json
&& rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```

3 RGB + Depth

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json
&& rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right','rgbd_hand_color','rgbd_hand_depth']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```
 
3 RGB + Depth + LiDAR

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected.json
&& rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right','rgbd_hand_color','rgbd_hand_depth','lidar_body']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```
 
#### Dataset corrected with odometry

1 RGB

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected_with_odometry.json && rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```


2 RGB

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected_with_odometry.json && rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```

3 RGB + Depth

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected_with_odometry.json && rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right','rgbd_hand_color','rgbd_hand_depth']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```
 
3 RGB + Depth + LiDAR

```bash
export CSF="lambda x: int(x) not in []" \
export DATASET=$ATOM_DATASETS/zau/inesc_day2_5_full/dataset_corrected_with_odometry.json && rosrun atom_calibration calibrate \
-json $DATASET -uic -v  \
-csf "$CSF" -ssf "lambda x: x in ['rgb_body_left','rgb_body_right','rgbd_hand_color','rgbd_hand_depth','lidar_body']" \
 -ftol 1e-4 -xtol 1e-4 -gtol 1e-4
 ```

# Results for each test

#### Dataset corrected

1 RGB

```bash
+------------+--------------------+
| Collection | rgb_body_left [px] |
+------------+--------------------+
|    000     |        ---         |
|    001     |        ---         |
|    002     |       0.2665       |
|    003     |       0.3003       |

|    058     |       0.3504       |
|    059     |       0.3547       |
|  Averages  |       0.4098       |
+------------+--------------------+

 ```


2 RGB

```bash
+------------+--------------------+---------------------+
| Collection | rgb_body_left [px] | rgb_body_right [px] |
+------------+--------------------+---------------------+
|    000     |        ---         |        0.3259       |
|    001     |        ---         |        0.2630       |
|    002     |       0.9531       |         ---         |
|    003     |       0.9448       |         ---         |

|    057     |        ---         |        0.3747       |
|    058     |       0.3895       |         ---         |
|    059     |       0.4016       |         ---         |
|  Averages  |       0.9745       |        0.4144       |
+------------+--------------------+---------------------+

 ```

3 RGB + Depth

```bash
 +------------+--------------------+---------------------+----------------------+---------------------+
| Collection | rgb_body_left [px] | rgb_body_right [px] | rgbd_hand_color [px] | rgbd_hand_depth [m] |
+------------+--------------------+---------------------+----------------------+---------------------+
|    000     |        ---         |       11.3465       |         ---          |        0.0049       |
|    001     |        ---         |        9.2635       |        3.1180        |        0.0061       |
|    002     |       3.2818       |         ---         |        4.4167        |        0.0078       |

|    056     |        ---         |        0.3934       |         ---          |         ---         |
|    057     |        ---         |        5.2616       |        3.8391        |        0.0046       |
|    058     |      11.0627       |         ---         |        3.8842        |        0.0075       |
|    059     |       6.2523       |         ---         |        1.8507        |        0.0080       |
|  Averages  |      11.6014       |        5.9815       |        4.5987        |        0.0063       |
+------------+--------------------+---------------------+----------------------+---------------------+

 ```
 
3 RGB + Depth + LiDAR

```bash
+------------+----------------+--------------------+---------------------+----------------------+-------------------- +
| Collection | lidar_body [m] | rgb_body_left [px] | rgb_body_right [px] | rgbd_hand_color [px] | rgbd_hand_depth [m] |
+------------+----------------+--------------------+---------------------+----------------------+-------------------- +
|    000     |     0.0096     |        ---         |       24.6825       |         ---          |        0.0059
|
|    001     |     0.0088     |        ---         |        9.6389       |        4.1972        |        0.0067
|
|    002     |     0.0101     |       2.0892       |         ---         |        5.0536        |        0.0082

|    059     |     0.0079     |       6.6032       |         ---         |        2.5755        |        0.0085
|
|  Averages  |     0.0136     |      14.2111       |        9.1966       |        5.3307        |        0.0095
|
+------------+----------------+--------------------+---------------------+----------------------+---------------------+
 ```
 
#### Dataset corrected with 

1 RGB

```bash
+------------+--------------------+
| Collection | rgb_body_left [px] |
+------------+--------------------+
|    000     |        ---         |
|    001     |        ---         |
|    002     |       0.2666       |

|    059     |       0.3547       |
|  Averages  |       0.4099       |
+------------+--------------------+

 ```


2 RGB

```bash
+------------+--------------------+---------------------+
| Collection | rgb_body_left [px] | rgb_body_right [px] |
+------------+--------------------+---------------------+
|    000     |        ---         |        0.3262       |
|    001     |        ---         |        0.2631       |
|    002     |       0.9529       |         ---         |

|    059     |       0.4018       |         ---         |
|  Averages  |       0.9748       |        0.4144       |
+------------+--------------------+---------------------+
 ```

3 RGB + Depth

```bash
+------------+--------------------+---------------------+----------------------+---------------------+
| Collection | rgb_body_left [px] | rgb_body_right [px] | rgbd_hand_color [px] | rgbd_hand_depth [m] |
+------------+--------------------+---------------------+----------------------+---------------------+
|    000     |        ---         |       145.1736      |         ---          |        0.0588       |
|    001     |        ---         |       199.0911      |       293.7285       |        0.0132       |
|    002     |      133.6360      |         ---         |       155.6511       |        0.0143       |

|    058     |      116.9550      |         ---         |       351.0738       |        0.0438       |
|    059     |      106.8883      |         ---         |       210.6804       |        0.0117       |
|  Averages  |      143.7929      |       141.2680      |       247.1236       |        0.0202       |
+------------+--------------------+---------------------+----------------------+---------------------+
 ```
 
3 RGB + Depth + LiDAR ( Was taking too long, couldn't finish, will edit later)

```bash
 ```

# Configuration file

```yaml
#
#           █████╗ ████████╗ ██████╗ ███╗   ███╗
#          ██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║
#          ███████║   ██║   ██║   ██║██╔████╔██║
#          ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║
#   __     ██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║    _
#  / _|    ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝   | |
#  | |_ _ __ __ _ _ __ ___   _____      _____  _ __| | __
#  |  _| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /
#  | | | | | (_| | | | | | |  __/\ V  V / (_) | |  |   <
#  |_| |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\
#  https://github.com/lardemua/atom
# Auto-generated file on 22/04/2024 22:06:02

# This yaml file describes your calibration!
description_file: "package://zau_description/urdf/zau.urdf.xacro"

bag_file: "$ROS_BAGS/zau/inesc_day2_final_final.bag"

world_link: "world"

sensors:

  rgbd_hand_color:
    link: "rgbd_hand_color_optical_frame"
    parent_link: "rgbd_hand_link"
    child_link: "rgbd_hand_color_frame"
    topic_name: "/rgbd_hand/color/image_raw"
    modality: "rgb"
    throttle: 10

  rgbd_hand_depth:
    link: "rgbd_hand_depth_optical_frame"
    parent_link: "rgbd_hand_link"
    child_link: "rgbd_hand_depth_frame"
    topic_name: "/rgbd_hand/depth/image_raw"
    modality: "depth"
    throttle: 10

  rgb_body_left:
    link: "rgb_body_left_optical_frame"
    parent_link: "base_link_mb"
    child_link: "rgb_body_left_link"
    topic_name: "/rgb_body_left/image_raw"
    modality: "rgb"
    throttle: 10

  rgb_body_right:
    link: "rgb_body_right_optical_frame"
    parent_link: "base_link_mb"
    child_link: "rgb_body_right_link"
    topic_name: "/rgb_body_right/image_raw"
    modality: "rgb"
    throttle: 

  lidar_body:
    link: "lidar_body"
    parent_link: "base_link_mb"
    child_link: "lidar_body_base_link"
    topic_name: "/lidar_body/points"
    modality: "lidar3d"
    throttle:

  vo_body_fisheye1:
    link: "vo_body_fisheye1_optical_frame"
    parent_link: "vo_body_link"
    child_link: "vo_body_fisheye1_frame"
    topic_name: "/vo_body/fisheye1/image_raw"
    modality: "rgb"
    throttle:
  
  vo_body_fisheye2:
    link: "vo_body_fisheye2_optical_frame"
    parent_link: "vo_body_link"
    child_link: "vo_body_fisheye2_frame"
    topic_name: "/vo_body/fisheye2/image_raw"
    modality: "rgb"
    throttle:

additional_tfs:
  base_link_mb_to_base_link:
   parent_link: "base_link_mb"
   child_link: "base_link"

joints:
calibration_patterns:

  pattern_1:
    link: "pattern_link"

    parent_link: "world" 

    fixed: true

    pattern_type: "charuco"

    dictionary: "DICT_5X5_100"

    mesh_file: "package://atom_worlds/pattern/models/charuco_800x600_5x5_100/charuco_800x600_5x5_100.dae"

    border_size: { 'x': 0.04, 'y': 0.03 }

    dimension: { "x": 11, "y": 8 }
    size: 0.06
    inner_size: 0.045
	
anchored_sensor:

max_duration_between_msgs: 1000

package_name: "zau_calibration"

version: 3.0

```
